version: '3.1'

services:
  app:
    image: blog-app
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: blog-app
    ports:
      - 80:80
    volumes:
      - ./:/user/src/app
    depends_on:
      - mongo
      - redis

  redis:
    image: redis
    container_name: blog-redis
    ports:
      - 6379:6379

  redis-insight:
    image: redislabs/redisinsight
    container_name: blog-redis-gui
    restart: always
    ports:
      - 8001:8001

  mongo:
    image: mongo
    restart: always
    container_name: blog-mongo
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    # volumes:
    #   - ./mongoDatafiles/:/data/db/:rw

  mongo-express:
    image: mongo-express
    container_name: blog-mongo-expr
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    depends_on:
      - mongo